name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy repository files for virtual machine Github Actions
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.3'
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install -q -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          flake8 .